### ISSUE TITLE
configure pagination amount

### ISSUE THREAD

**Issue by myurch** [autoinvent/conveyor-redux#17]
when instantiating conveyor-redux, one should be able to specify an 'amountPerPage' prop to specify how many should be returned. currently this is hard-coded at '20'

```
// todo: user should be able to specify this number when instantiating conveyor-redux reducer classes
export const DEFAULT_PAGINATION_AMT = 20
```

add to docs

**Comment by davidism** [comment]
I'd call it `defaultPerPage`. In the future this might not be the only config we need, we should consider how we might pass other configuration as well.
