### ISSUE TITLE
update for pagination

### ISSUE THREAD

**Issue by myurch** [autoinvent/conveyor-redux#19]
(should do this alongside of magql-query)

the reducer that takes care of FETCH_MODEL_INDEX should also be fire off during: consts.CHANGE_PAGE

alongside 'filter' and 'sort' should also return:

```
page: getPage({
        schema,
        modelName: payload.modelName,
        tableView: selectTableView(state$.value)
      })
```

and 

```
export const getPage = ({ schema, modelName, tableView }) => {
  const currentPage = R.pathOr(1, [modelName, 'page', 'currentPage'], tableView)
  return { current: currentPage, per_page: DEFAULT_PAGINATION_AMT }
}
```
(index begins at 1 now)

make sure DEFAULT_PAGINATION_AMT is the same for magql-query and conveyor-redux and they can both be configured with the same number

**Comment by itechify** [comment]
Believe this is done #15
