### ISSUE TITLE
fix ConveyorReducer overrides

### ISSUE THREAD

**Issue by myurch** [autoinvent/conveyor-redux#20]
if you have custom reducers which are created using ES6, then when they are uploaded into the 'overrides' and called "new Reducer(schema)" you get an error  

```
    R.forEachObjIndexed((Reducer, key) => {
      // @ts-ignore
      this[key] = new Reducer(schema)
    }, mergedReducerMap)
```

error: class constructors must be invoked with 'new'

most likely because we are using typescript, the two class types don't work well together. 

potential solution: required using redux-thunk OR change all reducers from classes to functions

**Comment by davidism** [comment]
working now according to @ChristopherCarson
