### ISSUE TITLE
Refactor: remove 'NOTFOUND' string in favor or null

### ISSUE THREAD

**Issue by ChristopherCarson** [autoinvent/conveyor-redux#37]
Currently to properly trigger a redirect when a model query fails, we are passing the string value of 'NOTFOUND' throughout conveyor-redux.
This should be refactored to simply a null value, as a null value is what properly triggers conveyor to redirect.

**Comment by SteveShell** [comment]
Replace 'NOTFOUND' with null #45 appears that it can close this issue
