### ISSUE TITLE
Refactor: paginate schema attribute

### ISSUE THREAD

**Issue by ChristopherCarson** [autoinvent/conveyor-redux#38]
A refactor is needed on the new paginate attribute.

1) It should be changed to pagible to match filterable and sortable.
2) We need to investigate if the logic for deactivating pagination is better moved to magql-builder instead of in conveyor-redux where it is currently being handled.
3) The schema should not be traversed to pull this value, it needs to have a helper method for retrieving it that allows the field to be dynamic (function or boolean)

**Comment by itechify** [comment]
No longer relevant since we are doing a larger refactor of conveyor-schema
