### ISSUE TITLE
Store/load user preference state

### ISSUE THREAD

**Issue by itechify** [autoinvent/conveyor-redux#58]
Store/load parts of the redux store in/from local storage (probably just dark mode preference?)

Requires #56 to be completed most likely.

Possibly use: https://github.com/rt2zz/redux-persist

**Comment by DanielHall977** [comment]
I've been playing around with redux-persist for MARC2-319, and I'm not sure it's a good idea. Most of the code required to implement persistence would need to be implemented by whatever application imports conveyor-redux, and can for just a little more effort implement all of it.
 
 
In order for persist to work 3 things need to happen:
 
 

    The application component needs to be wrapped in the PersistGate redux class.
     
    2. The store needs to be persisted.
     
     
    3.  And whatever reducer we want to persist is wrapped in a persist reduce function.
     
     
    1&2 can only be done by the application using conveyor
     
    3 can be done quite easily by the end user application by simply wrapping the rootReducer and persisting everything.
     
    If you only want to persist the userPreference reducer in conveyor-redux, then you need to either override its 'reduce' method, or have the makeReducers function pick out the userPreference reducer for persistence while building all the reducers in conveyor.
     
     
    (This on top of the fact that adding this will make conveyor-redux dependent on a new library, an still leave most of the necessary work undone)

**Comment by DanielHall977** [comment]
https://github.com/autoinvent/conveyor-redux/issues/58

**Comment by DanielHall977** [comment]
I can summarize all the necessary documentation for that with a link to redux persisit:  https://github.com/rt2zz/redux-persist
